cms/cms/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'',include('college.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^college/', include('college.urls', namespace = "college")),
    url(r'^student/', include('student.urls', namespace = "student")),
    url(r'^parent/', include('parent.urls', namespace = "parent")),
    url(r'^staff/', include('staff.urls', namespace = "staff")),
    url(r'^exam/', include('exam.urls', namespace = "exam")),
    url(r'^course/', include('course.urls', namespace = "course")),
    
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    ]



urlpatterns += [
    url(r'^captcha/', include('captcha.urls')),
]

cms/course/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views
from views import *
urlpatterns = [

url(r'^$', portal_main_page, name="portal_main_page"),url(r'^new/$', RegisterView.as_view(), name = 'new_course'),
url(r'^list/$', ListAllCourseView.as_view(), name='list_course'),
url(r'^update/(?P<pk>[\w-]+)/$', views.updatecourse ,name='course_update'),
url(r'^delete/(?P<pk>[\w-]+)/$', views.deletecourse ,name='course_delete'),
url(r'^detail/(?P<cid>[\w-]+)/$', views.coursedetail ,name='course_detail'),
url(r'^success/', SuccessView.as_view(), name = "course_success"),

url(r'^subject/new/$', RegisterSubjectView.as_view(), name = 'new_subject'),
url(r'^subject/list/$', ListAllSubjectView.as_view(), name='list_subject'),
url(r'^subject/update/(?P<pk>[\w-]+)/$', views.updatesubject, name='subject_update'),
url(r'^subject/delete/(?P<pk>[\w-]+)/$', views.deletesubject, name='subject_delete'),
url(r'^subject/success/', SuccessView.as_view(), name = "subject_success"),

]

cms/course/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
	name = models.CharField(max_length = 120)
	fees = models.IntegerField()
	eligibility = models.CharField(max_length = 120)
	duration = models.IntegerField(default = 3)
	noofsemesters = models.IntegerField(default = 6)
	desc = models.CharField(max_length = 220)
	totseats = models.IntegerField(default = 0)
	balseats = models.IntegerField(default = 0)
	
	def __str__(self):
		return self.name


class Subject(models.Model):
	name = models.CharField(max_length = 120)
	code = models.CharField(max_length = 160)
	desc = models.CharField(max_length = 120)
	course = models.ForeignKey(Course, related_name = "course_name")
	semester = models.CharField(max_length = 120)
	
	def __str__(self):
		return self.name

cms/course/forms.py
from django import forms
from captcha.fields import CaptchaField

from models import Course, Subject


class RegisterCourseForm(forms.ModelForm):
	captcha = CaptchaField()

	class Meta:
		model = Course
		fields = ['name','fees','eligibility','duration','noofsemesters','totseats','balseats','desc']

	def __init__(self,*args,**kwargs):
		super(RegisterCourseForm, self).__init__(*args, **kwargs)


class RegisterSubjectForm(forms.ModelForm):
	captcha = CaptchaField()

	class Meta:
		model = Subject
		fields = ['name','code','desc','course','semester']

	def __init__(self,*args,**kwargs):
		super(RegisterSubjectForm, self).__init__(*args, **kwargs)

cms/course/views.py
from django.shortcuts import render, render_to_response
from django.views.generic import TemplateView, View, ListView
from django.views.generic.edit import FormView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from django.core.urlresolvers import reverse

from models import Course, Subject
from forms import *

@login_required
def portal_main_page(request):
	template_name = "index.html"
	return render_to_response('admin_panel.html')

class SuccessView(TemplateView):
	template_name = "success.html"



class RegisterView(FormView):
	template_name = 'course/registration.html'
	form_class = RegisterCourseForm
	model = Course
	

	def get(self, request, *args, **kwargs):
		print("inside get--")
		course_form = RegisterCourseForm()
		return self.render_to_response(self.get_context_data(course_form = course_form))

	def get_success_url(self,**kwargs):
		print("work reverse lazy")
		return reverse_lazy('course:list_course')


	def post(self,request, *args, **kwargs):
		print("-------------inside post------------")
		
		course_form = RegisterCourseForm(self.request.POST)
		if (course_form.is_valid()):
			print("form valid returned-------------")
			return self.form_valid(course_form)
		else:
			print("------------form invalid returned............")
			return self.form_invalid(course_form)

	def form_valid(self,course_form):
		self.object = course_form.save()
		return super(RegisterView,self).form_valid(course_form)

	def form_invalid(self, course_form):
		return self.render_to_response(self.get_context_data(course_form = course_form))


class ListAllCourseView(View):
	template_name = "course/courselist.html"

	def get(self, request):
		print("inside get")
		courselist = Course.objects.all()
		return render_to_response(self.template_name, {'clist':courselist})

# ---------------------------------------------------

def updatecourse(request, pk):
    template_name='course/update_course.html'
    course = get_object_or_404(Course, pk=pk)
    form = RegisterCourseForm(request.POST or None, instance=course)
    if form.is_valid():
        form.save()
        return redirect('course:list_course')
    return render(request, template_name, {'form':form})

def updatesubject(request, pk):
    template_name='course/update_subject.html'
    subject = get_object_or_404(Subject, pk=pk)
    form = RegisterSubjectForm(request.POST or None, instance=subject)
    if form.is_valid():
        form.save()
        return redirect('course:list_subject')
    return render(request, template_name, {'form':form})

# -----------------------------------------

class RegisterSubjectView(FormView):
	template_name = 'course/new_subject.html'
	form_class = RegisterSubjectForm
	model = Subject
	

	def get(self, request, *args, **kwargs):
		print("inside get--")
		subject_form = RegisterSubjectForm()
		return self.render_to_response(self.get_context_data(subject_form = subject_form))

	def get_success_url(self,**kwargs):
		print("work reverse lazy")
		return reverse_lazy('course:list_subject')


	def post(self,request, *args, **kwargs):
		print("-------------inside post------------")
		
		subject_form = RegisterSubjectForm(self.request.POST)
		if (subject_form.is_valid()):
			print("form valid returned-------------")
			return self.form_valid(subject_form)
		else:
			print("------------form invalid returned............")
			return self.form_invalid(subject_form)

	def form_valid(self,subject_form):
		self.object = subject_form.save()
		return super(RegisterSubjectView,self).form_valid(subject_form)

	def form_invalid(self, subject_form):
		return self.render_to_response(self.get_context_data(subject_form = subject_form))


class ListAllSubjectView(View):
	template_name = "course/subjectlist.html"

	def get(self, request):
		print("inside get")
		subjectlist = Subject.objects.all()
		return render_to_response(self.template_name, {'slist':subjectlist})

# ---------------------------------------------------------


def deletesubject(request, pk):
    template_name='course/subject_confirm_delete.html'
    course = get_object_or_404(Subject, pk=pk)    
    if request.method=='POST':
        course.delete()
        return redirect('course:list_subject')
    return render(request, template_name, {'form':course})

def deletecourse(request, pk):
    template_name='course/course_confirm_delete.html'
    course = get_object_or_404(Course, pk=pk)    
    

    if request.method=='POST':
        course.delete()
       
        return redirect('course:list_course')
    return render(request, template_name, {'form':course})


	
# class DeleteSubject(DeleteView):
# 	model = Subject
# 	form_class = RegisterSubjectForm
# 	template_name = 'course/subject_delete.html'
# 	success_url = reverse_lazy('course:list_subject')


# class DeleteCourse(DeleteView):
# 	model = Course
# 	form_class = RegisterCourseForm
# 	template_name = 'course/delete.html'
# 	success_url = reverse_lazy('course:list_course')

# ---------------------------------------------------------




def coursedetail(request, cid):
	template_name='course/course_detail.html'
	course = get_object_or_404(Course, id= cid)
	subjectlist = Subject.objects.filter(course_id = cid) 
	print(course.name, course.fees)
	print(subjectlist)

	return render_to_response(template_name, {'slist':subjectlist})

cms/templates/course/course_confirm_delete.html
<html>
	<header>
		{% include 'base.html' %}
	</header>
	<body>
	<form method="post">{% csrf_token %}
	    Are you sure you want to delete "{{ form.name }}" ?
	    <input type="submit" value="Submit" />
	</form>
	</body>
	

</html>

cms/templates/course/course_detail.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Course list</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>

	<header>
		<div class="container">
			

		</div>
	</header>
	
	<body>
	
		
		<div class ="jumbotron">
			<div class="container">
				{% csrf_token %}
				{% if slist %}
				<h3>Subjects in {{slist.name}}</h3>
				<table class="table table-bordered ">
					<thead>
						<tr>
							<th>Subject Name</th>
							<th>Code</th>
							<th>Description</th>
							<th>Course</th>
							<th>Semester</th>
							
						
					</thead>
					<tbody>
						{% for s in slist %}
						<tr>

							<th>{{s.name}}</th>
							<th>{{s.code}}</th>
							<th>{{s.desc}}</th>
							<th>{{s.course}}</th>
							<th>{{s.semester}}</th>
							
							
						</tr>
						{% endfor %}
					</tbody>
				</table>
				{% else %}
					<p>Not Data </p>
				{% endif %}

	 		</div>
 		</div>

 		
	</body>
	<footer>
		
	</footer>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/course/courselist.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Course list</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="jumbotron">
			<div class="container">
				{% if clist %}
				<table class="table table-bordered ">
					<thead>
						<tr>
							<th>Course Name</th>
							<th>Fees</th>
							<th>Eligibility</th>
							<th>Duration</th>
							<th>Description</th>
							<th>Toatl No of Seats</th>
							<th>Number of seats available</th>
							<th>Edit</th>
							<th>Delete</th>
						</tr>
						
					</thead>
					<tbody>
						{% for c in clist %}
						<tr>
							<th><a href="{% url 'course:course_detail' c.id %}">{{c.name}}</a></th>
							<th>{{c.fees}}</th>
							<th>{{c.eligibility}}</th>
							<th>{{c.duration}}</th>
							<th>{{c.desc}}</th>
							<th>{{c.totseats}}</th>
							<th>{{c.balseats}}</th>
							<th><a href="{% url 'course:course_update' c.pk %}">Edit</a> </th>
							<th><a href="{% url 'course:course_delete' c.pk %}">Delete</a> </th>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				{% else %}
					<p>Not Data </p>
				{% endif %}
			</div>
 		</div>
	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/course/new_subject.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Course Registration</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container" align = "left left-justified">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h2>Course Registration</h2>
				</div>
						
				<div class="panel-body">
					
					<div class="jumbotron">
						<form action="{{ action }}" method="POST">
						{% csrf_token %}
							{% if subject_form.non_field_errors %}
								<ul>
									{% for error in subject_form.non_field_errors %}
							    		<li>{{ error }}</li>
							    	{% endfor %}
							    </ul>
							{% endif %}
							<table class="table table-striped">
								{% for field in subject_form %}
									<tr>
									<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<th>
										<div  id="{{ field.auto_id }}_label_tag">
										    {{ field.label_tag }} 
										</div>
										</th>
										<td>

										<div id="{{ field.auto_id }}_field">
											{{ field }}
										</div>

										<div id="{{ field.auto_id }}_errors">
											{{ field.errors }}
										</div>
										{{ field.help_text }}
										</td>
										</div>	
									</div>	
									</tr>
								{% endfor %}
							</table>

							<input id="save_course" type="submit" value="Save" />
					</form>
				</div>
			</div>

				<div class="panel-footer">
					<p>College Management System</p>
				</div>

			</div>






	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/course/registration.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Course Registration</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	
	<body>
		
		<div class="container" align = "left left-justified">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h2>Course Registration</h2>
				</div>
						
				<div class="panel-body">
					
					<div class="jumbotron">
						<form action="{{ action }}" method="POST">
						{% csrf_token %}
							{% if course_form.non_field_errors %}
								<ul>
									{% for error in course_form.non_field_errors %}
							    		<li>{{ error }}</li>
							    	{% endfor %}
							    </ul>
							{% endif %}
							<table class="table table-striped">
								{% for field in course_form %}
									<tr>
									<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<th>
										<div  id="{{ field.auto_id }}_label_tag">
										    {{ field.label_tag }} 
										</div>
										</th>
										<td>

										<div id="{{ field.auto_id }}_field">
											{{ field }}
										</div>

										<div id="{{ field.auto_id }}_errors">
											{{ field.errors }}
										</div>
										{{ field.help_text }}
										</td>
										</div>	
									</div>	
									</tr>
								{% endfor %}
							</table>

							<input id="save_course" type="submit" value="Save" />
					</form>
				</div>
			</div>

				<div class="panel-footer">
					<p>College Management System</p>
				</div>

			</div>
		</div>



 


	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/course/subject_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ form.name }}" ?
    <input type="submit" value="Submit" />
</form>

cms/templates/course/subjectlist.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Course list</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>

	
	
	<body>
	
		
		<div class ="jumbotron">
			<div class="container">
			
				{% if slist %}
				<table class="table table-bordered ">
					<thead>
						<tr>
							<th>Subject Name</th>
							<th>Code</th>
							<th>Description</th>
							<th>Course</th>
							<th>Semester</th>
							<th>Edit</th>
							<th>Delete</th>
						
					</thead>
					<tbody>
						{% for s in slist %}
						<tr>

							<th>{{s.name}}</th>
							<th>{{s.code}}</th>
							<th>{{s.desc}}</th>
							<th>{{s.course}}</th>
							<th>{{s.semester}}</th>
							<th><a href="{% url 'course:subject_update' s.pk %}">Edit</a></th>
							<th><a href="{% url 'course:subject_delete' s.pk %}">Delete</a></th>
							
						</tr>
						{% endfor %}
					</tbody>
				</table>
				{% else %}
					<p>Not Data </p>
				{% endif %}

	 		</div>
 		</div>

 		
	</body>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/course/update_course.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Course Registration</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container" align = "left left-justified">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h2>Course Registration</h2>
				</div>
						
				<div class="panel-body">
					
					<div class="jumbotron">
						<form action="{{ action }}" method="POST">
						{% csrf_token %}
							{% if form.non_field_errors %}
								<ul>
									{% for error in form.non_field_errors %}
							    		<li>{{ error }}</li>
							    	{% endfor %}
							    </ul>
							{% endif %}
							<table class="table table-striped">
								{% for field in form %}
									<tr>
									<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<th>
										<div  id="{{ field.auto_id }}_label_tag">
										    {{ field.label_tag }} 
										</div>
										</th>
										<td>

										<div id="{{ field.auto_id }}_field">
											{{ field }}
										</div>

										<div id="{{ field.auto_id }}_errors">
											{{ field.errors }}
										</div>
										{{ field.help_text }}
										</td>
										</div>	
									</div>	
									</tr>
								{% endfor %}
							</table>

							<input id="save_course" type="submit" value="Save" />
					</form>
				</div>
			</div>
				

				<div class="panel-footer">
					<p>College Management System</p>
				</div>

			</div>

	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>






<!-- <div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Course Name :</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="cname" value="{{course_update_obj.name}}" >
							</div>
						</div>				
	
						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Fees :</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="fees" value="{{course_update_obj.fees}}" placeholder="{{course_update_obj.fees}}">
							</div>
						</div>		

						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Eligibility :</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="eligibility" value="{{course_update_obj.eligibility}}" placeholder="{{course_update_obj.eligibility}}">
							</div>
						</div>	

						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Duration :</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="duration" value="{{course_update_obj.duration}}" placeholder="{{course_update_obj.duration}}">
							</div>
						</div>	

						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Number of semesters :</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="noofsemesters" value="{{course_update_obj.noofsemesters}}" placeholder="{{course_update_obj.noofsemesters}}">
							</div>
						</div>	
						
						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Description:</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="desc" value="{{course_update_obj.desc}}" placeholder="{{course_update_obj.desc}}">
							</div>
						</div>	

						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Total Seats</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="totseats" value="{{course_update_obj.totseats}}" placeholder="{{course_update_obj.totseats}}">
							</div>
						</div>

						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Total Seats</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="balseats" value="{{course_update_obj.balseats}}" placeholder="{{course_update_obj.balseats}}">
							</div>
						</div>
 -->

cms/templates/course/update_subject.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Course Registration</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container" align = "left left-justified">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h2>Subject Update</h2>
				</div>
						
				<div class="panel-body">
					
					<form action = "." method = "post" align = "center" class="form-horizontal">
					
					 
						{% csrf_token %}
						{{form.as_p}}

						
						
						
						<button type ="update">Edit</button>
						 
					</form>
				</div>

				<div class="panel-footer">
					<p>College Management System</p>
				</div>

			</div>

	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>






<!-- <div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Course Name :</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="cname" value="{{course_update_obj.name}}" >
							</div>
						</div>				
	
						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Fees :</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="fees" value="{{course_update_obj.fees}}" placeholder="{{course_update_obj.fees}}">
							</div>
						</div>		

						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Eligibility :</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="eligibility" value="{{course_update_obj.eligibility}}" placeholder="{{course_update_obj.eligibility}}">
							</div>
						</div>	

						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Duration :</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="duration" value="{{course_update_obj.duration}}" placeholder="{{course_update_obj.duration}}">
							</div>
						</div>	

						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Number of semesters :</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="noofsemesters" value="{{course_update_obj.noofsemesters}}" placeholder="{{course_update_obj.noofsemesters}}">
							</div>
						</div>	
						
						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Description:</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="desc" value="{{course_update_obj.desc}}" placeholder="{{course_update_obj.desc}}">
							</div>
						</div>	

						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Total Seats</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="totseats" value="{{course_update_obj.totseats}}" placeholder="{{course_update_obj.totseats}}">
							</div>
						</div>

						<div class="row" align = "center">
							<div class="col-sm-3 col-md-3 col-xs-3 col-lg-3">
								<label>Total Seats</label>
							</div>
							<div class="col-sm-5 col-md-5 col-xs-5 col-lg-5">
								<input type = text" name ="balseats" value="{{course_update_obj.balseats}}" placeholder="{{course_update_obj.balseats}}">
							</div>
						</div>
 -->