cms/cms/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'',include('college.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^college/', include('college.urls', namespace = "college")),
    url(r'^student/', include('student.urls', namespace = "student")),
    url(r'^parent/', include('parent.urls', namespace = "parent")),
    url(r'^staff/', include('staff.urls', namespace = "staff")),
    url(r'^exam/', include('exam.urls', namespace = "exam")),
    url(r'^course/', include('course.urls', namespace = "course")),
    
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    ]



urlpatterns += [
    url(r'^captcha/', include('captcha.urls')),
]

cms/exam/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from views import *
from . import views
urlpatterns = [

url(r'^$', portal_main_page, name="portal_main_page"),
url(r'^new/$', RegisterView.as_view(), name = 'new_exam'),
url(r'^list/$', ListAllExamView.as_view(), name='list_exam'),
url(r'^update/(?P<pk>[\w-]+)/$', views.updateexam, name='update_exam'),
url(r'^delete/(?P<pk>[\w-]+)/$', views.deleteexam, name='delete_exam'),
url(r'^success/', SuccessView.as_view(), name = "exam_success"),

]

cms/exam/models.py
from django.db import models
from course.models import Course, Subject
# Create your models here.

class ExamType(models.Model):
	examtypename = models.CharField(max_length = 120)
	desc = models.CharField(max_length = 220)
	def __str__(self):
		return self.examtypename

class Exam(models.Model):
	course = models.ForeignKey(Course, related_name = 'courseid_exam')
	semester = models.IntegerField(default = 1)
	examname = models.CharField(max_length = 220, default = None)
	examtypename = models.ForeignKey(ExamType, related_name = "examtype_examtype")
	examdesc = models.CharField(max_length = 220, default = None)
	startdate = models.DateTimeField()
	enddate = models.DateTimeField()

	def __str__(self):
		return self.examname

class ExamDetails(models.Model):
	exam = models.ForeignKey(Exam, related_name = 'examid_examdetails')
	examdate = models.DateTimeField()
	subjectid = models.ForeignKey(Subject, related_name = 'subjectid_examdetails')
	desc = models.CharField(max_length = 120)

	def __str__(self):
		return self.examid

cms/exam/forms.py
from django import forms
from captcha.fields import CaptchaField

	

from course.models import Course, Subject
from exam.models import *

class ExamForm(forms.ModelForm):
	captcha = CaptchaField()
	class Meta:
		model = Exam
		fields = ['course','semester','examname','examtypename','examdesc','startdate','enddate']

	def __init__(self,*args,**kwargs):
		super(ExamForm, self).__init__(*args, **kwargs)

class ExamDetailsForm(forms.ModelForm):
	captcha = CaptchaField()
	class Meta:
		model = ExamDetails
		fields = []

cms/exam/views.py
from django.shortcuts import render, render_to_response
from django.views.generic import TemplateView, View, ListView
from django.views.generic.edit import FormView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect

from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from models import Course, Subject
from exam.forms import *

@login_required
def portal_main_page(request):
	template_name = "index.html"
	return render_to_response('admin_panel.html')
class SuccessView(TemplateView):
	template_name = "success.html"

class RegisterView(FormView):
	template_name = 'exam/registration.html'
	form_class = ExamForm
	model = Exam
	

	def get(self, request, *args, **kwargs):
		print("inside get--")
		exam_form = ExamForm()
		return self.render_to_response(self.get_context_data(exam_form = exam_form))

	def get_success_url(self,**kwargs):
		print("work reverse lazy")
		return reverse_lazy('exam:list_exam')


	def post(self,request, *args, **kwargs):
		print("-------------inside post------------")
		
		exam_form = ExamForm(self.request.POST)
		if (exam_form.is_valid()):
			print("form valid returned-------------")
			return self.form_valid(exam_form)
		else:
			print("------------form invalid returned............")
			return self.form_invalid(exam_form)

	def form_valid(self,exam_form):
		self.object = exam_form.save()
		return super(RegisterView,self).form_valid(exam_form)

	def form_invalid(self, exam_form):
		return self.render_to_response(self.get_context_data(exam_form = exam_form))


class ListAllExamView(View):
	template_name = "exam/examlist.html"

	def get(self, request):
		print("inside get")
		examlist = Exam.objects.all()
		return render_to_response(self.template_name, {'elist':examlist})

def deleteexam(request, pk):
    template_name='exam/exam_confirm_delete.html'
    exam = get_object_or_404(Exam, pk=pk)    
    if request.method=='POST':
        exam.delete()
        return redirect('exam:list_exam')
    return render(request, template_name, {'form':exam})

def updateexam(request, pk):
    template_name='exam/update_exam.html'
    exam = get_object_or_404(Exam, pk=pk)
    form = ExamForm(request.POST or None, instance=exam)
    if form.is_valid():
        form.save()
        return redirect('exam:list_exam')
    return render(request, template_name, {'form':form})

# ---------------------------------------------------------

cms/templates/exam/exam_confirm_delete.html
<html>
<body>


<form method="post">{% csrf_token %}
	<div class="container">
		<h3>Are you sure you want to delete "{{ form.examname }}" for {{form.course}} ?
	   This will delete all data associated with {{form.examname}}</h3>
		<input type="submit" value="Submit" />
    </div>

</form>



</body>
</html>

cms/templates/exam/examlist.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Exam list</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container">
		<h2>Exam List</h2>
		{% if elist %}
		<table class="table table-bordered ">
			<thead>
				<tr>
					<th>Course Name</th>
					<th>Semester</th>
					<th>Exam Type</th>
					<th>Description</th>
					<th>Start Date</th>
					<th>End Date</th>
					<th>Edit</th>
					<th>Delete</th>
				</tr>
				
			</thead>
			<tbody>
				{% for e in elist %}
				<tr>
						<th>{{e.course}}</th>
						<th>{{e.semester}}</th>
						<th>{{e.examname}}</th>
						<th>{{e.examtypename}}<t/h>
						<th>{{e.examdesc}}</th>
						<th>{{e.startdate}}</th>
						<th>{{e.enddate}}</th>
						<th><a href="{% url 'exam:update_exam' e.pk %}">Edit</a></th>
						<th><a href="{% url 'exam:delete_exam' e.pk %}">Delete</a></th>

					
				</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<p>Not Data </p>
	{% endif %}

 		
		</div>
 		
	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/exam/registration.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Course Registration</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container" align = "left left-justified">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h2>Course Registration</h2>
				</div>
						
				<div class="panel-body">
					
					<div class="jumbotron">
						<form action="{{ action }}" method="POST">
						{% csrf_token %}
							{% if exam_form.non_field_errors %}
								<ul>
									{% for error in exam_form.non_field_errors %}
							    		<li>{{ error }}</li>
							    	{% endfor %}
							    </ul>
							{% endif %}
							<table class="table table-striped">
								{% for field in exam_form %}
									<tr>
									<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<th>
										<div  id="{{ field.auto_id }}_label_tag">
										    {{ field.label_tag }} 
										</div>
										</th>
										<td>

										<div id="{{ field.auto_id }}_field">
											{{ field }}
										</div>

										<div id="{{ field.auto_id }}_errors">
											{{ field.errors }}
										</div>
										{{ field.help_text }}
										</td>
										</div>	
									</div>	
									</tr>
								{% endfor %}
							</table>

							<input id="save_course" type="submit" value="Save" />
					</form>
				</div>
			</div>

				<div class="panel-footer">
					<p>College Management System</p>
				</div>

			</div>






	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/exam/update.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Edit</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>

	<body>
	<div class = "container" align = "left">
		<form action = "." method="post">
			{% csrf_token %}
			{{exam_form.as_p}}
			<button class = "btn btn-info" type = "update">Save Changes</button>

		</form>
		</div>
	</body>


	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>
</html>


Edit

cms/templates/exam/update_exam.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Course Registration</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container" align = "left left-justified">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h2>Edit Exam</h2>
				</div>
						
				<div class="panel-body">
					
					<div class="jumbotron">
						<form action="{{ action }}" method="POST">
						{% csrf_token %}
							{% if form.non_field_errors %}
								<ul>
									{% for error in form.non_field_errors %}
							    		<li>{{ error }}</li>
							    	{% endfor %}
							    </ul>
							{% endif %}
							<table class="table table-striped">
								{% for field in form %}
									<tr>
									<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<th>
										<div  id="{{ field.auto_id }}_label_tag">
										    {{ field.label_tag }} 
										</div>
										</th>
										<td>

										<div id="{{ field.auto_id }}_field">
											{{ field }}
										</div>

										<div id="{{ field.auto_id }}_errors">
											{{ field.errors }}
										</div>
										{{ field.help_text }}
										</td>
										</div>	
									</div>	
									</tr>
								{% endfor %}
							</table>

							<input id="save_course" type="submit" value="Save" />
					</form>
				</div>
			</div>
				

				<div class="panel-footer">
					<p>College Management System</p>
				</div>

			</div>

	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>