cms/cms/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'',include('college.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^college/', include('college.urls', namespace = "college")),
    url(r'^student/', include('student.urls', namespace = "student")),
    url(r'^parent/', include('parent.urls', namespace = "parent")),
    url(r'^staff/', include('staff.urls', namespace = "staff")),
    url(r'^exam/', include('exam.urls', namespace = "exam")),
    url(r'^course/', include('course.urls', namespace = "course")),
    
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    ]



urlpatterns += [
    url(r'^captcha/', include('captcha.urls')),
]

cms/course/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views
from views import *
urlpatterns = [

url(r'^$', portal_main_page, name="portal_main_page"),url(r'^new/$', RegisterView.as_view(), name = 'new_course'),
url(r'^list/$', ListAllCourseView.as_view(), name='list_course'),
url(r'^update/(?P<pk>[\w-]+)/$', views.updatecourse ,name='course_update'),
url(r'^delete/(?P<pk>[\w-]+)/$', views.deletecourse ,name='course_delete'),
url(r'^detail/(?P<cid>[\w-]+)/$', views.coursedetail ,name='course_detail'),
url(r'^success/', SuccessView.as_view(), name = "course_success"),

url(r'^subject/new/$', RegisterSubjectView.as_view(), name = 'new_subject'),
url(r'^subject/list/$', ListAllSubjectView.as_view(), name='list_subject'),
url(r'^subject/update/(?P<pk>[\w-]+)/$', views.updatesubject, name='subject_update'),
url(r'^subject/delete/(?P<pk>[\w-]+)/$', views.deletesubject, name='subject_delete'),
url(r'^subject/success/', SuccessView.as_view(), name = "subject_success"),

]

cms/exam/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from views import *
from . import views
urlpatterns = [

url(r'^$', portal_main_page, name="portal_main_page"),
url(r'^new/$', RegisterView.as_view(), name = 'new_exam'),
url(r'^list/$', ListAllExamView.as_view(), name='list_exam'),
url(r'^update/(?P<pk>[\w-]+)/$', views.updateexam, name='update_exam'),
url(r'^delete/(?P<pk>[\w-]+)/$', views.deleteexam, name='delete_exam'),
url(r'^success/', SuccessView.as_view(), name = "exam_success"),

]

cms/parent/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from views import *
from . import views

urlpatterns = [

url(r'^$', portal_main_page, name="portal_main_page"),url(r'^new/$', RegisterView.as_view(), name = 'new_parent'),
url(r'^list/$', ListAllParentView.as_view(), name='list_parent'),
url(r'^update/(?P<uid>[\w-]+)/(?P<pid>[\w-]+)/$', views.updateparent, name='update_parent'),
url(r'^delete/(?P<uid>[\w-]+)/(?P<pid>[\w-]+)/$', views.deleteparent, name='delete_parent'),
url(r'^success/', SuccessView.as_view(), name = "parent_success"),
]

cms/staff/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from views import *
from . import views

urlpatterns = [

url(r'^$', portal_main_page, name="portal_main_page"),url(r'^new/$', RegisterView.as_view(), name = 'new_staff'),
url(r'^list/$', ListAllStaffView.as_view(), name='list_staff'),
url(r'^update/(?P<uid>[\w-]+)/(?P<sid>[\w-]+)/$', views.updatestaff, name='update_staff'),
url(r'^delete/(?P<uid>[\w-]+)/(?P<sid>[\w-]+)/$', views.deletestaff, name='delete_staff'),
url(r'^success/', SuccessView.as_view(), name = "staff_success"),

]

cms/templates/admin_panel.html
 <html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Home</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container">
			                          
			<div class="container">
				
					<h2>College Management System :Admin Panel</h2>

				<div class="nav nav-tabs">

					<li class="dropdown">
					<a href ="#">College Detail </a>
						
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Student Detail<span class="caret"></span></a>
							<ul class="dropdown-menu"> 
								<li><a href="{% url 'student:new_student' %}">New Student</a></li>
								<li><a href="{% url 'student:list_student' %}">List Student</a></li>
								
							</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Parent Detail<span class="caret"></span></a>
							<ul class="dropdown-menu"> 
								<li><a href="{% url 'parent:new_parent' %}">New Parent</a></li>
								<li><a href="{% url 'parent:list_parent' %}">List Parent</a></li>
								
							</ul>
					</li>

					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Staff Detail<span class="caret"></span></a>
							<ul class="dropdown-menu"> 
								<li><a href="{% url 'staff:new_staff' %}">New Staff</a></li>
								<li><a href="{% url 'staff:list_staff' %}">List Staff</a></li>
								
							</ul>
					</li>

					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Course Detail<span class="caret"></span></a>
							<ul class="dropdown-menu"> 
								<li><a href="{% url 'course:new_course' %}">New Course</a></li>
								<li><a href="{% url 'course:list_course' %}">List Course</a></li>
								<li><a href="{% url 'course:new_subject' %}">New Subject</a></li>
								<li><a href="{% url 'course:list_subject' %}">List Subject</a></li>
								
							</ul>
					</li>

					
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Exam Detail<span class="caret"></span></a>
							<ul class="dropdown-menu"> 
								<li><a href="{% url 'exam:new_exam' %}">New Exam</a></li>
								<li><a href="{% url 'exam:list_exam' %}">List Exam</a></li>
								
							</ul>
					</li>
					
					<!-- <li><a href="#">{{request.user}}</a></li>
					</li> -->
					
					<li><a href="/logout">Logout</a></li>
					
				</div>

			</div>
			

		</div>
	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/footer.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>tab</title>
		<meta charset="utf-8">

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      	
      	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
      	</script>
    </head>

    <body>
    	<div class="container">
        
            <ul class="nav nav-tabs" >
                <li><a href="{% url 'college:college_index' %}">College Panel</a></li>
                <li><a href="{% url 'parent:parent_index' %}">Parent Panel</a></li>
                <li><a href="{% url 'staff:staff_index' %}">Staff Panel</a></li>
                <li><a href="{% url 'course:course_index' %}">Course Panel</a></li>
                <li><a href="{% url 'exam:exam_index' %}">Exam Panel</a></li>
            </ul>
    	</div>



    </body>
</html>

cms/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <title>Home</title>
</head>

<body>
    {% if user.is_authenticated %}
    <p>hello</p>
    <p>welcome {{ user.username }}</p>
    <p><a href="/logout">Logout</a></p>
    {% else %}
    <p><a href="/login">Login</a></p>
    <p><a href="/register">Register</a></p>
    {% endif %}
</body>

</html>

cms/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>CollegeName| Home :: CollegeName</title>
<!-- Meta tag Keywords -->
<meta name="viewport" content="width=device-width, initial-scale=1">


<!-- css files -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
<link href ="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
</script>


</head>
<body>
<div class="mainlayouts" id="home">
	<div class = "conatiner">
		<div class ="jumbtron">
		<!--//top-bar-->
		<!-- navigation -->
			<div class ="top-nav">
				<nav class="navbar navbar-default">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							
						</div>
						<!-- navbar-header -->
						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							<ul class="nav navbar-nav navbar-left">
								<li><a href="#" class="hvr-underline-from-center active">Home</a></li>
								<li><a href="#about" class="hvr-underline-from-center scroll">About Us</a></li>
								

							</ul>
					
							<ul class="nav navbar-nav navbar-right">
								
								<li><a href="{% url 'login' %}"" <i class="fa fa-key" aria-hidden="true"></i>LOGIN</a></li>
								
								<!-- <li><a href="{%}" data-toggle="modal" data-target="#myModal4"><i class="fa fa-lock" aria-hidden="true"></i>REGISTER</a></li> -->
							</ul>
							
						</div>
						<div class="clearfix"> </div>	
				</nav>
			</div>
	<!-- //navigation -->
	</div>
</div>	




	<!--top-bar-->
	
	
	<!-- Modal3 -->
		<div class="modal fade" id="myModal3" tabindex="-1" role="dialog" >
			<div class="modal-dialog" role="document">
			<!-- Modal content-->
				<div class="modal-content news">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal">&times;</button>
							<h4>Login</h4>
							<!--newsletter-->
							<div class="login-main">
							  <form action="#" method="post">
								<input type="email" placeholder="Email" required="" name="Email">
								<input type="password" placeholder="Password" name="Password">
								<input type="submit" value="Login">
							</form>
							</div>
						<!--//newsletter-->			
						</div>
					</div>
				</div>
			 </div>
			<div class="clearfix"></div>
	<!-- //Modal3 -->

	<!-- Modal4 -->
		<div class="modal fade" id="myModal4" tabindex="-1" role="dialog" >
			<div class="modal-dialog" role="document">
			<!-- Modal content-->
				<div class="modal-content news">


						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal">&times;</button>
							<h4>Register Now</h4>
							<!--newsletter-->
							<div class="login-main">
							<form action="#" method="post">
								<input type="text" placeholder="Name" name="Name">
								<input type="email" placeholder="Email" required="" name="Email">
								<input type="password" placeholder="Password" name="Password">
								<input type="password" placeholder="Confirm Password" name="Password">
								<input type="text" placeholder="Phone Number" name="Number">
								<input type="submit" value="Register Now">
							</form>
							</div>
						<!--//newsletter-->			
						</div>
					</div>
				</div>
			 </div>
			<div class="clearfix"></div>
	<!-- //Modal4-->


					<div class="clearfix"></div>
	

	
<!--main-content-->

<!--about-->
		<div class="panel panel-info">
				<div class="panel-heading"  align = "center">
					<h1>About <span>us</span></h1>				
				</div>
						
				<div class="panel-body"  align = "center">

					<div id="about" class="about">
						<div class="container">
								
								<h2>Since 1980, we have been in the educational industry, providing quality education</h2>
								<div class="specialty-grids-top">
									<div class="col-md-4 service-box" >
										<figure class="icon">
											<span class="glyphicon glyphicon-education a1" aria-hidden="true"></span>
										</figure>
										<h5>Quality Infrstructure</h5>
										<p>Top notch quality infrstructure for quality learning and best experience</p>
									</div>
									<div class="col-md-4 service-box wow bounceIn animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
										<figure class="icon">
											<span class="glyphicon glyphicon-home a2" aria-hidden="true"></span>
										</figure>
										<h5>Experienced faculties</h5>
										<p>We have expeienced and quality equipments staff, the best you know it</p>
									</div>
									<div class="col-md-4 service-box wow bounceIn animated" data-wow-delay="0.4s">
										<figure class="icon">
											 <span class="glyphicon glyphicon-leaf a3" aria-hidden="true"></span>						
										</figure>
										<h5>Experience</h5>
										<p>The best learning experience you can have, is here</p>
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="buttons">
									<div class="button">
										<h5><a href="#contact" class="scroll" id="Contact">Contact with us</a></h5>
									</div>
									<div class="button2">
										<h5><a href="#" data-toggle="modal" data-target="#myModal2">Admission Now</a></h5>
									</div>
								</div>
								<!-- Modal1 -->
								<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" >
									<div class="modal-dialog" role="document">
									<!-- Modal content-->
										<div class="modal-content abt">
												<div class="modal-header">
													<button type="button" class="close clo1" data-dismiss="modal">&times;</button>
														<h4>Enter the Following Details</h4>
														<form action="#" method="post" class="mod2">
															<ul>
																<li class="text">Name of Applicant :  </li>
																<li class="agileits-main"><input name="name" type="text" required></li>
															</ul>
															<ul>
																<li class="text">Date of Birth :  </li>
																<li class="agileits-main"><input name="organization" type="text" required></li>
															</ul>
															<ul>
																<li class="text">Father Name  :  </li>
																<li class="agileits-main"><input name="name" type="text" required></li>
															</ul>
															<ul>
																<li class="text">Gender  :  </li>
																<li class="agileits-main"><input name="contact" type="text" required></li>
															</ul>
															<ul>
																<li class="text">mobile no  :  </li>
																<li class="agileits-main"><input name="mobile" type="text" required></li>
															</ul>
															<ul>
																<li class="text">Address  :  </li>
																<li class="agileits-main"><input name="mobile" type="text" required></li>
															</ul>
															<ul>
																<li class="text">District  :  </li>
																<li class="agileits-main"><input name="mobile" type="text" required></li>
															</ul>
															<ul>
																<li class="text">State  :  </li>
																<li class="agileits-main"><input name="mobile" type="text" required></li>
															</ul>
															<div class="clear"></div>
															<div class="agile-submit">
																<input type="submit" value="submit">
															</div>
														</form>

												</div>
											</div>
										</div>
									 </div>
									<!-- //Modal1 -->
									<div class="clearfix"></div>
								</div>
						</div>
						<div class="about-info">
							<img src="../images/ab.jpg" alt="about-image">
							<div class="right-agile">
								<h5>Information</h5>
								<p>Established in June 1980, with its own distinct identity and tradition has been serving as the tower of learning for many generations. It has moulded the destiny of hundreds of people for a better tomorrow. The College has emerged as a leading centre for teaching, learning, and research in the field of higher education in South India. It is a great land mark in the history of the college that it was declared as an autonomous college in 2014 by the University Grants.</p>

								<h5>Our Motto</h5>
								<p>“CARITAS VERA NOBILITAS”<br>(Charity is true Nobility)</p>
							</div>
						</div>
						<div class="clearfix"></div>
					<!--//about-->

						
				</div>

				<div class="panel-footer" align >
				
					<div class="footer" id="footer">

						<div class="container">
							<ul class="nav navbar-nav navbar-right">
								Project by Kishor
							
							
							
							<div class="clearfix"> </div>
							
						</div>
					</div>
				</div>

			</div>






<!-- //footer -->

<!-- js -->
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>



<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>

cms/templates/login.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Login</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
	</head>

	<body>
		<div class="container" align = "left left-justified">
			<div class="panel panel-info">
				<div class="panel-heading">

					<h2>Login</h2>
				</div>
						
				<div class="panel-body">
					<div class ="jumbotron">
					<form action="{{ action }}" method="POST">
						{% csrf_token %}
							{% if form.non_field_errors %}
								<ul>
									{% for error in form.non_field_errors %}
							    		<li>{{ error }}</li>
							    	{% endfor %}
							    </ul>
							{% endif %}
							<table class="table table-striped">
							{% for field in form %}
								<tr>
								<div class="row" align = "left" id="{{ field.auto_id }}_container">
									

									<div class = "clearfix">
										
									 		<div class="col-md-4">
									 		<th>
									    		{{ field.label_tag }} 
									    		</th>
									    		<td>{{ field }}
											</div>

											<div class="clearfix">

											</div>
											<td>
											<div  class="col-md-2" id="{{ field.auto_id }}_errors">
												{{ field.errors }}
											</div>
											</td>
											<td>
											{{ field.help_text }}
											</td>
									</div>
								</div>	
								</tr>
							{% endfor %}

							
							</table>
								
							<button class = "btn btn-info">login</button>
					</form>
					<br>
				<button class = "btn btn-default"> <span class="fa fa-github"><a href="{% url 'social:begin' 'github' %}">Login with GitHub</a></span></button>
					
				<button class= "btn btn-info"><span class="fa fa-twitter"></span><a href="{% url 'social:begin' 'twitter' %}">Login with Twitter</a></button>	 

				</div>

				<div class="panel-footer">
					<p>College Management System</p>
				</div>
			</div>
			
		</div>

		<!-- <div class = "container" align = "left">
			<form method = "post">
				{% csrf_token %}
				{{form.as_p}}
				
				<button class = "btn btn-info">login</button>
			</form>		
		</div> -->
	</body>


	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>
</html>

cms/templates/stuent_panel.html
 <html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Home</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container">
			                          
			<div class="container">
				
					<h2>College Management System :Student Panel</h2>

				<div class="nav nav-tabs">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Course Detail<span class="caret"></span></a>
							<ul class="dropdown-menu"> 
								<li><a href="{% url 'course:list_course' %}">List Course</a></li>
								<li><a href="{% url 'course:list_subject' %}">List Subject</a></li>
								
							</ul>
					</li>

					
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Exam Detail<span class="caret"></span></a>
							<ul class="dropdown-menu"> 
								<li><a href="{% url 'exam:new_exam' %}">New Exam</a></li>
								<li><a href="{% url 'exam:list_exam' %}">List Exam</a></li>
								
							</ul>
					</li>
					
					<li><a href="/logout">Logout</a></li>
					
				</div>

			</div>
		</div>
		<div class = "container">
			{% include 'student/profile.html' %}

		</div>
			}
	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/teacher_panel.html
 <html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Home</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container">
			                          
			<div class="container">
				
					<h2>College Management System :Teacher Panel</h2>

				
					
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Exam Detail<span class="caret"></span></a>
							<ul class="dropdown-menu"> 
								<li><a href="{% url 'exam:new_exam' %}">New Exam</a></li>
								<li><a href="{% url 'exam:list_exam' %}">List Exam</a></li>
								
							</ul>
					</li>

					<div class="nav nav-tabs">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Students Details<span class="caret"></span></a>
							<ul class="dropdown-menu"> 
								<li><a href="{% url 'student:list_student' %}">List Students</a></li>
																
							</ul>
					</li>

					
					<li><a href="/logout">Logout</a></li>
					
				</div>

			</div>
			

		</div>
	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>