cms/cms/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'',include('college.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^college/', include('college.urls', namespace = "college")),
    url(r'^student/', include('student.urls', namespace = "student")),
    url(r'^parent/', include('parent.urls', namespace = "parent")),
    url(r'^staff/', include('staff.urls', namespace = "staff")),
    url(r'^exam/', include('exam.urls', namespace = "exam")),
    url(r'^course/', include('course.urls', namespace = "course")),
    
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    ]



urlpatterns += [
    url(r'^captcha/', include('captcha.urls')),
]

cms/staff/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from views import *
from . import views

urlpatterns = [

url(r'^$', portal_main_page, name="portal_main_page"),url(r'^new/$', RegisterView.as_view(), name = 'new_staff'),
url(r'^list/$', ListAllStaffView.as_view(), name='list_staff'),
url(r'^update/(?P<uid>[\w-]+)/(?P<sid>[\w-]+)/$', views.updatestaff, name='update_staff'),
url(r'^delete/(?P<uid>[\w-]+)/(?P<sid>[\w-]+)/$', views.deletestaff, name='delete_staff'),
url(r'^success/', SuccessView.as_view(), name = "staff_success"),

]

cms/student/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from views import *
from . import views

urlpatterns = [

url(r'^$', portal_main_page, name="portal_main_page"),
url(r'^new/$', RegisterView.as_view(), name = 'new_student'),
url(r'^list/$', ListAllStudentView.as_view(), name='list_student'),
url(r'^update/(?P<pk>[\w-]+)/$',UpdateStudent.as_view() ,name='student_update'),
url(r'^delete/(?P<pk>[\w-]+)/$', DeleteStudent.as_view(), name='student_delete'),

url(r'^success/', SuccessView.as_view(), name = "student_success"),
]

cms/staff/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime   
# Create your models here.
class Staff(models.Model):
	user = models.OneToOneField(User, related_name = "staff_user")
	createdOn = models.DateTimeField(auto_now= True)
	age = models.IntegerField(default = 15)
	#dob = models.DateTimeField()
	designation = models.CharField(max_length = 120)
	housename = models.CharField(max_length = 120)
	place = models.CharField(max_length = 120)
	district = models.CharField(max_length = 120)
	state = models.CharField(max_length = 120)
	nationality = models.CharField(max_length = 120)
	contact = models.IntegerField(default = 0)
	altcontact = models.IntegerField(default = 0)

	def __str__(self):
		return self.user.first_name
	

cms/staff/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from captcha.fields import CaptchaField

from staff.models import *


class RegisterForm(UserCreationForm):
	first_name = forms.CharField(required = True)
	last_name = forms.CharField(required = True)
	email = forms.EmailField(required = True)
	username = forms.CharField(required = True)

	class Meta:
		model = User
		fields = ('first_name','last_name','email','username','password1','password2')

	def __init__(self,*args, **kwargs):
		super(RegisterForm, self).__init__(*args, **kwargs)

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2:
			if password1 != password2:
				print("invalid password")
				raise forms.ValidationError("Password mismatch")
			return password2

	def clean_email(self):
		
		if self.cleaned_data.get('email')== '':
			print("invalid email")
			raise forms.ValidationError("invalid email")
		else:
			return self.cleaned_data.get('email')
	
	
	

class StaffForm(forms.ModelForm):
	captcha = CaptchaField()
	class Meta:
		model = Staff
		exclude = ('user',)

	def __init__(self,*args,**kwargs):
		super(StaffForm, self).__init__(*args, **kwargs)

cms/staff/views.py
from django.shortcuts import render, render_to_response
from django.views.generic import TemplateView, View, ListView
from django.views.generic.edit import FormView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from django.core.urlresolvers import reverse

from forms import *
# Create your views here.

@login_required
def portal_main_page(request):
	template_name = "index.html"
	return render_to_response('admin_panel.html')

class SuccessView(TemplateView):
	template_name = "staff/success.html"

class RegisterView(FormView):
	template_name = 'staff/registration.html'
	form_class = RegisterForm
	model = User
	

	def get(self, request, *args, **kwargs):
		print("inside get--")
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		profile_form = StaffForm()
		return self.render_to_response(self.get_context_data(form = form, profile_form=profile_form))

	def get_success_url(self,**kwargs):
		print("work reverse lazy")
		return reverse_lazy('staff_success')

	def post(self,request, *args, **kwargs):
		print("-------------inside post------------")
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		profile_form = StaffForm(self.request.POST)
		if (form.is_valid() and profile_form.is_valid()):
			print("form valid returned-------------")
			return self.form_valid(form, profile_form)
		else:
			print("------------form invalid returned............")
			return self.form_invalid(form,profile_form)

	def form_valid(self,form, profile_form):
		self.object = form.save()
		p_form = profile_form.save(commit = False)
		p_form.user = self.object
		p_form.save()
		return super(RegisterView,self).form_valid(form)

	def form_invalid(self, form, profile_form):
		return self.render_to_response(self.get_context_data(form = form,profile_form = profile_form))


class ListAllStaffView(View):
	template_name = "staff/stafflist.html"

	def get(self, request):
		print("inside get")
		stafflist = Staff.objects.all()
		return render_to_response(self.template_name, {'stlist':stafflist})

def updatestaff(request, uid, sid):
	template_name='staff/update_staff.html'
	staff = get_object_or_404(Staff, id= sid) 
	staff_user = get_object_or_404(User, id = uid)   
	print("staff name--", staff.user.first_name)
	print("staff age-- ",staff.age)
	form = RegisterForm(request.POST or None, instance=staff_user)
	profile_form = StaffForm(request.POST or None, instance=staff)
	if form.is_valid():
		form.save()
		profile_form.save()
		return redirect('staff:list_staff')
	return render(request, template_name, {'form':form, 'profile_form':profile_form})

# ---------------------------------------------------------
def deletestaff(request,uid,sid):
	template_name='staff/staff_confirm_delete.html'
	staff = get_object_or_404(Staff, id= sid) 
	staff_user = get_object_or_404(User, id = uid)   
	print("staff name--", staff.user.first_name)
	print("staff age-- ",staff.age)
	if request.method=='POST':
		staff.delete()
		staff_user.delete()
		return redirect('staff:list_staff')
	return render(request, template_name, {'form':staff})

cms/templates/staff/registration.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Staff Registration</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container" align = "left left-justified">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h2>Staff Registration</h2>
				</div>
						
				<div class="panel-body">
					<div class ="jumbotron">
					<form action="{{ action }}" method="POST">
						{% csrf_token %}
							{% if form.non_field_errors %}
								<ul>
									{% for error in form.non_field_errors %}
							    		<li>{{ error }}</li>
							    	{% endfor %}
							    </ul>
							{% endif %}
							<table class="table table-striped">
							{% for field in form %}
								<tr>
								<div class="row" align = "left" id="{{ field.auto_id }}_container">
									

									<div class = "clearfix">
										
									 		<div class="col-md-4">
									 		<th>
									    		{{ field.label_tag }} 
									    		</th>
									    		<td>{{ field }}
											</div>

											<div class="clearfix">

											</div>
											<td>
											<div  class="col-md-2" id="{{ field.auto_id }}_errors">
												{{ field.errors }}
											</div>
											</td>
											<td>
											{{ field.help_text }}
											</td>
									</div>
								</div>	
								</tr>
							{% endfor %}

							{% if profile_form.non_field_errors %}
								<ul>
									{% for error in profile_form.non_field_errors %}
							    		<li>{{ error }}</li>
							    	{% endfor %}
							    </ul>
							{% endif %}
							
							{% for field in profile_form %}
								<tr>
								<div class="row" align = "left" id="{{ field.auto_id }}_container">
									

									<div class = "clearfix">
										<div class="col-md-4">
										 	<th>
										    	{{ field.label_tag }} 
										    </th>
									    	<td>{{ field }}</td>
										</div>
										<div class="clearfix">
										</div>

										
										<div  class="col-md-2" id="{ field.auto_id }}_errors">
											<td>{{ field.errors }}</td>
										</div>
										
										<td>
										{{ field.help_text }}
										</td>
									</div>
								</div>	
								</tr>
							{% endfor %}
							</table>
								
							<input id="save_course" type="submit" value="Save" />
					</form>
				</div>

				<div class="panel-footer">
					<p>College Management System</p>
				</div>
			</div>
		

	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/staff/staff_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ form.user.first_name }} {{ form.user.last_name }}" ?
    <input type="submit" value="Submit" />
</form>

cms/templates/staff/stafflist.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Staff list</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container">
		<!-- {{stdlist}}	 -->
		{% if stlist %}
		<h2>Staff List</h2>
		<table class="table table-bordered ">
			<thead>
				<tr>

					<th>First Name</th>
					<th>Last Name</th>
					<th>Username</th>
					<th>Designation</th>
					<th>place</th>
					<th>contact Number</th>
					<th>Edit</th>
					<th>Delete</th>
					
				</tr>
				
			</thead>
			<tbody>
				{% for st in stlist %}
				<tr>
					<th>{{st.user.first_name}}</th>
					<th>{{st.user.last_name}}</th>
					<th>{{st.user.username}}</th>
					<th>{{st.designation}}</th>
					<th>{{st.place}}</th>
					<th>{{st.contact}}</th>
					<th><a href="{% url 'staff:update_staff' st.user.id st.id %}">Update</a></th>
					<th><a href="{% url 'staff:delete_staff' st.user.id st.id %}">Delete</a></th>
					
					
				</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<p>Not Data </p>
	{% endif %}


		</div>
	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/staff/success.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Student_panel index</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container">
			<h1>Registration successful</h1>
			
			<h4><a href="{% url 'staff:staff_index'  %}">Go back to Staff</a></h4>

			<h2><a href="{% url 'staff:new_student' %}">New Staff</a><h2>
		</div>
	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>

cms/templates/staff/update_staff.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Update Staff details</title>
				
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	</head>
	<body>
		<div class="container" align = "left left-justified">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h2>Staff details update</h2>
				</div>
						
				<div class="panel-body">
					
					<div class="jumbotron">
						<form action="{{ action }}" method="POST">
						{% csrf_token %}
							{% if form.non_field_errors %}
								<ul>
									{% for error in form.non_field_errors %}
							    		<li>{{ error }}</li>
							    	{% endfor %}
							    </ul>
							{% endif %}
							<table class="table table-striped">
								{% for field in form %}
									<tr>
									<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<th>
										<div  id="{{ field.auto_id }}_label_tag">
										    {{ field.label_tag }} 
										</div>
										</th>
										<td>

										<div id="{{ field.auto_id }}_field">
											{{ field }}
										</div>

										<div id="{{ field.auto_id }}_errors">
											{{ field.errors }}
										</div>
										{{ field.help_text }}
										</td>
										</div>	
									</div>	
									</tr>
								{% endfor %}

							{% if profile_form.non_field_errors %}
								<ul>
									{% for error in profile_form.non_field_errors %}
							    		<li>{{ error }}</li>
							    	{% endfor %}
							    </ul>
							{% endif %}

							{% for field in profile_form %}
									<tr>
									<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<div class="row" align = "left" id="{{ field.auto_id }}_container">
										<th>
										<div  id="{{ field.auto_id }}_label_tag">
										    {{ field.label_tag }} 
										</div>
										</th>
										<td>

										<div id="{{ field.auto_id }}_field">
											{{ field }}
										</div>

										<div id="{{ field.auto_id }}_errors">
											{{ field.errors }}
										</div>
										{{ field.help_text }}
										</td>
										</div>	
									</div>	
									</tr>
								{% endfor %}
							</table>

							<input id="save_course" type="submit" value="Save" />
					</form>
				</div>
			</div>
				

				<div class="panel-footer">
					<p>College Management System</p>
				</div>

			</div>

	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
	</script>
	      	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
	</script>

</html>